export const GET_ERRORS = 'GET_ERRORS';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_RELEVANT_NEWS = 'GET_RELEVANT_NEWS';
export const GET_RELEVANT_LOADING = 'GET_RELEVANT_LOADING'; 
export const GET_PREGNANCY_NEWS = 'GET_PREGNANCY_NEWS';
export const GET_PREGNANCY_LOADING = 'GET_PREGNANCY_LOADING'; 
export const GET_CHARITY_NEWS = 'GET_CHARITY_NEWS';
export const GET_CHARITY_LOADING = 'GET_CHARITY_LOADING';
export const GET_ALL_NEWS = "GET_ALL_NEWS";

export const GET_BENEFACTORS = "GET_BENEFACTORS";
export const BENEFACTORS_LOADING = "BENEFACTORS_LOADING";

export const GET_VOLUNTEERS = "GET_VOLUNTEERS";
export const VOLUNTEERS_LOADING= "VOLUNTEERS_LOADING";